### ISSUE TITLE
Morning session - peer to peer

### ISSUE THREAD

**Issue by ayaderaghul** [baqar-abbas/Portfolio-Project-Final-version#6]
You really did an amazing job on your portfolio project. Everything is looking pretty. The only thing we would suggest is: It is better to use an html tag `<section>, <article>` instead of `<div>` tags in your index.html file.

https://www.w3schools.com/tags/tag_section.asp

**Comment by baqar-abbas** [comment]
Thank you for your suggestions morning team(Fuad and Chi) I would surely try and incorporate your suggested options in my coming projects. 
Regards,
Baqar Abbas
